services:
  postgres:
    image: binarybunker_postgresimg
    container_name: BinaryBunker-postgres
    build:
      context: .
      dockerfile: Dockerfile
      #Port mapping for security reasons
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT_VIRTUELL}"
    environment:
      #create postgres user
      POSTGRES_USER: "${POSTGRES_JDBC_USER}"
      #create postgres password
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      #volume for persist data outside the container's lifecycle
    volumes:
      - postgres_data:/var/lib/postgresql/data
    #command to reduce possible connections to 4(=MIN) which safes performance
    command: postgres -c max_connections=4

volumes:
  postgres_data:
    driver: local