-- noinspection SqlResolveForFile

DROP TABLE IF EXISTS questions, promptQuestions;
DROP TYPE IF EXISTS osi_layer, difficulty_categories, questionTypeMC, questionTypePrompt;

CREATE TYPE osi_layer AS ENUM ('L1_PHYSICAL', 'L2_DATA_LINK', 'L3_NETWORK', 'L4_TRANSPORT');
CREATE TYPE difficulty_categories AS ENUM ('EASY', 'MEDIUM', 'DIFFICULT');
CREATE TYPE questionTypeMC AS ENUM ('NAT', 'DEFINITIONS','SWITCHING','IPV4','SUBNETTING','IPV6', 'TCP');
CREATE TYPE  questionTypePrompt AS ENUM ('WHICH_PREFIX_IN_SAME_SUBNET','FIND_NET_ID','FIND_IP_IN_SUBNET','FIND_BROADCAST','FIND_NET_ID_AND_BROADCAST','FIND_MASK','FIND_OCTET','FIND_BINARY_OCTET','NUMBER_OF_DEVICES','MAC_TO_IID','IID_TO_MAC');

CREATE TABLE questions (
    id SERIAL PRIMARY KEY,
    osiLayer osi_layer NOT NULL,
    difficulty difficulty_categories NOT NULL,
    questiontype questionTypeMC[]  NOT NULL,
    data JSONB NOT NULL
);
CREATE TABLE promptQuestions(
    id SERIAL PRIMARY KEY,
    osiLayer osi_layer NOT NULL,
    questionTypePrompt QuestionTypePrompt NOT NULL,
    data JSONB NOT NULL
);
CREATE TABLE counter (
    countQuestions INTEGER NOT NULL DEFAULT 0
);
INSERT INTO counter (countQuestions) VALUES (0);

INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What does the abbreviation LAN stand for?", "explanation": "LAN is short for Local Area Network, linking computers in a singular physical location.", "allAnswers": {"1": "Linking Areas Network", "2": "Local Area Network", "3": "Linked Area Network", "4": "Localized Area Network"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What does the abbreviation MAN stand for?", "explanation": "MAN stands for Metropolitan Area Network, linking LANs together r in a wider area like a city.", "allAnswers": {"1": "Mega Area Network", "2": "Multi Area Network", "3": "Metropolitan Area Network", "4": "Master Area Network"}, "correctAnswers": ["3"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What does the abbreviation WAN stand for?", "explanation": "WAN stands for Wide Area Network, linking different networks over large distances.", "allAnswers": {"1": "World Area Network", "2": "Wide Area Network", "3": "West Area Network", "4": "Working Area Network"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "Which of these combinations are abbreviations for network types?", "explanation": "LAN, MAN and WAN are all valid abbreviations for Local, Metropolitan and Wide Area Network.", "allAnswers": {"1": "LAN, MAN, WAN", "2": "LAN, BAN, MAN", "3": "LAN, CAN, DAN", "4": "MAC, LAC, DAC"}, "correctAnswers": ["1"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What does P2P stand for?", "explanation": "P2P stands for Point-To-Point when talking about networks, meaning two machines conversing with each other (like a Router and a single computer).", "allAnswers": {"1": "Point-To-Point", "2": "Player-To-Player", "3": "Party-To-Party", "4": "Package-To-Party"}, "correctAnswers": ["1"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What does P2MP stand for?", "explanation": "P2MP stands for Point-To-Multipoint, meaning one computer sends to multiple recipients.", "allAnswers": {"1": "Point-To-MessagePoint", "2": "Point-To-MeetingPoint", "3": "Point-To-MasterPoint", "4": "Point-To-MultiPoint"}, "correctAnswers": ["4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "Which transmission type would be most likely suitable to send an E-Mail?", "explanation": "An E-Mail can be sent without needing a response, so Unicasting (Unilateral communication) is sufficient.", "allAnswers": {"1": "Unicast", "2": "Multicast", "3": "Broadcast", "4": "Anycast"}, "correctAnswers": ["1"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "Which transmission type would be most likely suitable to deliver an ARP request?", "explanation": "ARP requests have to be sent to every participant in a network, so broadcast would be applicable.", "allAnswers": {"1": "Unicast", "2": "Multicast", "3": "Broadcast", "4": "Anycast"}, "correctAnswers": ["4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What is it called when two computers can talk to each other alternatingly, but not simultaneously?", "explanation": "When senders and recipients take turns it is called Half-Duplex.", "allAnswers": {"1": "Simplex", "2": "Half-Duplex", "3": "Full-Duplex", "4": "Multiplex"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What type of connection is a phone call?", "explanation": "A phone transmits and receives at the same time (bidirectional and simultaneous).", "allAnswers": {"1": "Simplex", "2": "Half-Duplex", "3": "Duplex", "4": "Gigaplex"}, "correctAnswers": ["3"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','MEDIUM','{DEFINITIONS}'::questionTypeMC[],'{"question": "What type of communication is IPv4?", "explanation": "IPv4 transmits packets connectionlessly.", "allAnswers": {"1": "Packet SWITCHING + Connectionless", "2": "Circuit SWITCHING + Connectionless", "3": "Packet SWITCHING + Connection Oriented", "4": "Circuit SWITCHING + Connection Oriented"}, "correctAnswers": ["1"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L4_TRANSPORT','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What type of communication is TCP?", "explanation": "TCP establishes a connection to ensure packets arrive.", "allAnswers": {"1": "Connection-Oriented", "2": "Connectionless"}, "correctAnswers": ["1"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What type of communication does ARP use?", "explanation": "ARP is a connection-oriented protocol.", "allAnswers": {"1": "Connection-Oriented", "2": "Connectionless"}, "correctAnswers": ["1"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L4_TRANSPORT','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "What type of communication is UDP?", "explanation": "UDP sends packets without checking if they actually arrived.", "allAnswers": {"1": "Connection-Oriented", "2": "Connectionless"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "Which OSI Layer is the Physical Layer?", "explanation": "The physical layer is the lowest Layer, layer 1.", "allAnswers": {"1": "1", "2": "2", "3": "3", "4": "4"}, "correctAnswers": ["1"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "Which OSI Layer is the Link Layer?", "explanation": "The Link Layer concerns SWITCHING via MAC-Addresses, one layer above physical.", "allAnswers": {"1": "1", "2": "2", "3": "3", "4": "4"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "Which OSI Layer is the Network Layer?", "explanation": "The network layer is the third layer, one above the Link Layer, encoding those packets and sending them between networks.", "allAnswers": {"1": "1", "2": "2", "3": "3", "4": "4"}, "correctAnswers": ["3"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L1_PHYSICAL','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "Which OSI Layer is the Transport Layer?", "explanation": "The transport layer encompasses all protocols used for end to end communication like TCP, UDP and so on.", "allAnswers": {"1": "1", "2": "2", "3": "3", "4": "4"}, "correctAnswers": ["4"]}'::jsonb);

INSERT INTO questions(osilayer, difficulty, questionType, data) VALUES('L2_DATA_LINK','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "Can computers communicate with a switch directly?", "explanation": "No, switches aren''t active participants in a network, they are functionally invisible to the clients.", "allAnswers": {"1": "Yes", "2": "No"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions(osilayer, difficulty, questionType, data) VALUES('L2_DATA_LINK','EASY','{SWITCHING}'::questionTypeMC[],'{"question": "What addresses do L2-Switches use to direct traffic?", "explanation": "Switches use the devices hardware addresses (MAC-Addresses).", "allAnswers": {"1": "Home Address", "2": "MAC Address", "3": "IP-Address", "4": "Neural Chip ID"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions(osilayer, difficulty, questionType, data) VALUES('L2_DATA_LINK','EASY','{SWITCHING}'::questionTypeMC[],'{"question": "If a target isn''t in a Switches SAT, how does it find the recipient?", "explanation": "If the target isn''t in the Switches source address table, a Broadcast is sent.", "allAnswers": {"1": "ARP Request", "2": "Broadcast", "3": "Denial of Distribution (DOD)", "4": "Randomly"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions(osilayer, difficulty, questionType, data) VALUES('L2_DATA_LINK','MEDIUM','{DEFINITIONS,SWITCHING}'::questionTypeMC[],'{"question": "What makes an L3-Switch different from an L2-Switch?", "explanation": "L3-Switches have routing capabilities, i.e. can route IP packets.", "allAnswers": {"1": "Their serial numbers have three Ls.", "2": "They have an IP-Address.", "3": "They always have firewalls installed.", "4": "They have routing functionality."}, "correctAnswers": ["2", "4"]}'::jsonb);
INSERT INTO questions(osilayer, difficulty, questionType, data) VALUES('L2_DATA_LINK','EASY','{SWITCHING}'::questionTypeMC[],'{"question": "What does a L2-Switch use to ensure packets are delivered correctly?", "explanation": "FCS stands for Frame-Check-Sequence, a sequence of bits which is used to ensure packet integrity.", "allAnswers": {"1": "FCS", "2": "TCP-Header", "3": "Store-And-Forward", "4": "UDP Responses"}, "correctAnswers": ["1", "2"]}'::jsonb);
INSERT INTO questions(osilayer, difficulty, questionType, data) VALUES('L2_DATA_LINK','EASY','{SWITCHING}'::questionTypeMC[],'{"question": "How can looping be prevented in a network?", "explanation": "Spanning Tree prevent loops from occurring by blocking redundant paths.", "allAnswers": {"1": "while(false) {...}", "2": "Anti-Loop-Routing", "3": "Spanning-Tree-Protocol", "4": "Spamming-Bee-Protocol"}, "correctAnswers": ["3"]}'::jsonb);
INSERT INTO questions(osilayer, difficulty, questionType, data) VALUES('L2_DATA_LINK','MEDIUM','{SWITCHING}'::questionTypeMC[],'{"question": "What is required to enable Spanning-Tree to work?", "explanation": "All options are required.", "allAnswers": {"1": "Every Bridge has Spanning-Tree-Multicast support", "2": "Every bridge has a unique ID", "3": "Every Port has a unique ID", "4": "Every Port has a relative priority"}, "correctAnswers": ["1", "2", "3", "4"]}'::jsonb);
INSERT INTO questions(osilayer, difficulty, questionType, data) VALUES('L2_DATA_LINK','MEDIUM','{SWITCHING}'::questionTypeMC[],'{"question": "Which kind of switching is more reliable?", "explanation": "Store-and-Forward can check the packet integrity because it stores the whole packet before sending it.", "allAnswers": {"1": "Cut-Through", "2": "Store-And-Forward"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions(osilayer, difficulty, questionType, data) VALUES('L2_DATA_LINK','MEDIUM','{SWITCHING}'::questionTypeMC[],'{"question": "Which kind of switching is more reliable?", "explanation": "Store-and-Forward can check the packet integrity because it stores the whole packet before sending it.", "allAnswers": {"1": "Cut Through", "2": "Store and Forward"}, "correctAnswers": ["2"]}'::jsonb);

INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{DEFINITIONS}'::questionTypeMC[],'{"question": "Which of the following is a primary function of OSI Layer 3?", "explanation": "The Network Layer (Layer 3) is responsible for routing, logical addressing (e.g., IP addresses), and determining the best path for data to travel between devices on different networks.", "allAnswers": {"1": "Error detection and correction", "2": "Logical addressing and routing", "3": "Data encryption for secure transmission", "4": "Flow control and session management"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{DEFINITIONS,IPV4}'::questionTypeMC[],'{"question": "Which of the following features is associated with IPv4?", "explanation": "IPv4 (Internet Protocol version 4) is a widely used protocol that uses a 32-bit addressing scheme, supports fragmentation, and is connectionless.", "allAnswers": {"1": "128-bit addressing", "2": "Connectionless communication", "3": "Built-in encryption", "4": "32-bit addressing"}, "correctAnswers": ["2", "4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{DEFINITIONS,IPV4}'::questionTypeMC[],'{"question": "Which of the following is a characteristic of IPv4 addresses?", "explanation": "IPv4 addresses are 32-bit numerical labels written in dotted decimal notation (e.g., 192.168.1.1), dictated by their subnet mask.", "allAnswers": {"1": "Written in hexadecimal format", "2": "Uses a 32-bit addressing scheme", "3": "Divided into network and host portions", "4": "Supports 128-bit addresses"}, "correctAnswers": ["2", "3"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{IPV4,SUBNETTING}'::questionTypeMC[],'{"question": "What is the primary purpose of subnetting in IPv4 networks?", "explanation": "Subnetting divides a larger network into smaller, manageable sub-networks. This improves network organization, optimizes IP address allocation, and enhances security and performance by isolating network traffic within subnets.", "allAnswers": {"1": "To convert IPv4 to IPv6", "2": "To divide a network into smaller, more efficient segments", "3": "To reduce the number of available IP addresses", "4": "To enhance network performance and security"}, "correctAnswers": ["2", "4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','MEDIUM','{IPV4,SUBNETTING}'::questionTypeMC[],'{"question": "Which of the following is true about subnet masks in IPv4 subnetting?", "explanation": "A subnet mask defines the portion of an IP address that represents the network and host parts. It is used to determine which subnet an IP address belongs to and is critical for routing and communication within and between networks.", "allAnswers": {"1": "Subnet masks are written in dotted decimal notation.", "2": "A subnet mask of 255.255.255.0 corresponds to a /24 prefix.", "3": "Subnet masks are used to convert IPv4 to IPv6.", "4": " A subnet mask ids needed to find the broadcast address."}, "correctAnswers": ["1", "2", "4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{DEFINITIONS,IPV4,SUBNETTING}'::questionTypeMC[],'{"question": "What is the main advantage of Variable Length Subnet Masking (VLSM) in IPv4?", "explanation": "VLSM allows the creation of subnets with different sizes by using subnet masks of varying lengths. This enables more efficient IP address utilization by assigning smaller subnets to networks with fewer hosts and larger subnets to networks with more hosts.", "allAnswers": {"1": "Reduces the need for routing protocols", "2": "Enables efficient utilization of IP addresses", "3": "Requires all subnets to have the same size", "4": "Allows subnet masks of varying lengths within the same network"}, "correctAnswers": ["2", "4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{IPV4}'::questionTypeMC[],'{"question": "Which of the following is a key function of a router in a network?", "explanation": "Routers operate at OSI Layer 3 and are responsible for forwarding packets between different networks based on their destination IP addresses. They use routing tables and protocols to determine the best path for data to travel.", "allAnswers": {"1": "Forward packets based on MAC addresses", "2": "Determine the best path to a destination network", "3": "Fragment and reassemble data at the Transport Layer", "4": "Use SAT tables to manage network traffic"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{IPV4}'::questionTypeMC[],'{"question": "Which protocol is used by a router to forward packets in a local subnet?", "explanation": "When a router needs to forward a packet to a device on the same local subnet, it uses ARP to resolve the MAC address corresponding to the destination IP address (or the next-hop IP address in the routing table).", "allAnswers": {"1": "ICMP", "2": "VLSM", "3": "MVP", "4": "ARP"}, "correctAnswers": ["4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','DIFFICULT','{IPV4}'::questionTypeMC[],'{"question": "Which of the following statements about ARP (Address Resolution Protocol) is correct?", "explanation": "ARP is a critical protocol used to map IP addresses to MAC addresses within a local network. It involves sending broadcast requests and receiving unicast replies. However, ARP has limitations, such as susceptibility to spoofing attacks, which can compromise network security.", "allAnswers": {"1": "ARP requests are sent as unicast packets to the target device.", "2": "ARP tables store mappings of MAC addresses to IP addresses for remote networks.", "3": "Gratuitous ARP can be used to detect IP address conflicts on the network.", "4": "ARP is used to resolve MAC addresses for devices on the same subnet."}, "correctAnswers": ["3", "4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','DIFFICULT','{IPV4,SUBNETTING}'::questionTypeMC[],'{"question": "Given the network address 192.168.10.0/24, what is the first valid host address in the subnet 192.168.10.128/25?", "explanation": "The subnet mask /25 indicates a subnet with a 128 address range (from .128 to .255). The first valid host address is the first IP address after the network address, which is 192.168.10.129, as the network address 192.168.10.128 is reserved.", "allAnswers": {"1": "192.168.10.128", "2": "192.168.10.129", "3": "192.168.10.255", "4": "192.168.10.0"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','DIFFICULT','{IPV4}'::questionTypeMC[],'{"question": "Given the network address 10.0.0.0/22, what is the last valid host address in the subnet 10.0.0.0/23?", "explanation": "The /23 subnet mask splits the 10.0.0.0/22 network into two subnets: 10.0.0.0/23 and 10.0.2.0/23. The last valid host address in the 10.0.0.0/23 subnet is 10.0.0.254, as the network address 10.0.0.0 and the broadcast address 10.0.0.255 are reserved.", "allAnswers": {"1": "10.0.0.254", "2": "10.0.0.255", "3": "10.0.0.0", "4": "10.0.1.255"}, "correctAnswers": ["1"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','MEDIUM','{IPV4}'::questionTypeMC[],'{"question": "Which of the following IP address ranges corresponds to a Class B network?", "explanation": "Class B IP addresses range from 128.0.0.0 to 191.255.255.255. These addresses use a default subnet mask of 255.255.0.0, providing a larger number of hosts per network compared to Class A but fewer than Class C.", "allAnswers": {"1": "10.0.0.0 - 10.255.255.255", "2": "128.0.0.0 - 191.255.255.255", "3": "192.0.0.0 - 223.255.255.255", "4": "224.0.0.0 - 239.255.255.255"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','MEDIUM','{IPV6}'::questionTypeMC[],'{"question": "Which of the following IP address ranges is used for link-local addresses in IPv6?", "explanation": "Link-local addresses in IPv6 are used for communication within the same network segment or link. They are automatically assigned to devices and are not routable beyond the local link. The address range for link-local addresses is fe80::/10, meaning addresses that start with \"fe80\" through \"febf\".", "allAnswers": {"1": "192.168.0.0 - 192.168.255.255", "2": "169.254.0.0 - 169.254.255.255", "3": "2001::/32", "4": "fe80::/10"}, "correctAnswers": ["4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{IPV4}'::questionTypeMC[],'{"question": "Which IP address is commonly used to refer to the localhost in IPv4?", "explanation": "The IPv4 address 127.0.0.1 is reserved for the localhost. It is used to refer to the local machine and allows it to communicate with itself. This address is commonly used for testing and troubleshooting network configurations.", "allAnswers": {"1": "0.0.0.0", "2": "192.168.0.1", "3": "127.0.0.1", "4": "10.0.0.1"}, "correctAnswers": ["3"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','MEDIUM','{IPV4}'::questionTypeMC[],'{"question": "What is the IP-Address 127.0.0.1 usually called?", "explanation": "127.0.0.1 is used by computers to make requests to themselves, therefore \"loop back\" to the \"local host\".", "allAnswers": {"1": "Link Local", "2": "Localhost", "3": "Class A", "4": "Loopback"}, "correctAnswers": ["2", "4"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','MEDIUM','{IPV6}'::questionTypeMC[],'{"question": "What is the IPv6 address used for the loopback interface?", "explanation": "In IPv6, the loopback address is ::1. It is used to refer to the local machine and is similar to the IPv4 address 127.0.0.1.", "allAnswers": {"1": "::0", "2": "::1", "3": "2001::1", "4": "fe80::1"}, "correctAnswers": ["2"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','EASY','{DEFINITIONS,IPV6}'::questionTypeMC[],'{"question": "What is the standard prefix used in SLAAC routing?", "explanation": "SLAAC routing uses the /64 prefix.", "allAnswers": {"1": "128", "2": "24", "3": "64", "4": "32"}, "correctAnswers": ["3"]}'::jsonb);
INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES('L3_NETWORK','MEDIUM','{IPV4,SUBNETTING}'::questionTypeMC[],'{"question": "What is the subnet mask for a network with a /28 prefix length?", "explanation": "A /28 prefix length means there are 28 bits used for the network portion of the address, leaving 4 bits for host addresses.", "allAnswers": {"1": "255.255.255.128", "2": "255.255.255.192", "3": "255.255.255.240"}, "correctAnswers": ["3"]}'::jsonb);

INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','WHICH_PREFIX_IN_SAME_SUBNET'::questionTypePrompt,'{"question": "What is the highest possible prefix so that these two IP''s are in the same subnet?", "explanation": "Assess the IP''s binary representation and check, up to which bit their representation is identical. That is the last bit of the Net-ID, therefore its index is the prefix."}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','FIND_NET_ID'::questionTypePrompt,'{"question": "Find the Net-ID for this IP-Address and prefix:", "explanation": "The Net-ID can be calculated by converting the IP to binary and nulling every host bit (every bit after the amount of bits signified by the prefix)"}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','FIND_IP_IN_SUBNET'::questionTypePrompt,'{"question": "Find an IP in the subnet of this address:", "explanation": "Determine the bounds of the subnet by nulling or setting all host bits to 1 and pick an address between those bounds."}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','FIND_BROADCAST'::questionTypePrompt,'{"question": "Find the broadcast address for this IP:", "explanation": "Write the address in its binary representation and set all host bits to 1."}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','FIND_NET_ID_AND_BROADCAST'::questionTypePrompt,'{"question": "Find the Net-ID and Broadcast-Address for this IP:", "explanation": "Write the address in its binary representation and set all host bits to 1 for the Broadcast ID, null them for the Net-ID."}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','FIND_MASK'::questionTypePrompt,'{"question": "Find the Subnet-Mask for this IP-Address:", "explanation": "To find the mask, set the first amount of bits to 1 according to the prefix, the rest should be zeroes. Convert this number to decimal to get the Subnet-Mask."}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','FIND_OCTET'::questionTypePrompt,'{"question": "Find the significant octet that is assessed when calculating the Net-ID in decimal representation:", "explanation": "An octet is a byte, so we have to assess which 8 bits the prefix affects. To find which of the four octets are affected, divide the prefix by 8 and round up to the next whole number."}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','FIND_BINARY_OCTET'::questionTypePrompt,'{"question": "Find the significant octet that is assessed when calculating the Net-ID in binary representation:", "explanation": "An octet is a byte, so we have to assess which 8 bits the prefix affects. To find which of the four octets are affected, divide the prefix by 8 and round up to the next whole number."}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','NUMBER_OF_DEVICES'::questionTypePrompt,'{"question": "Calculate the number of devices that can receive an IP-Address in this subnet:", "explanation": "There can be 2 to the power of host bits addresses in any given subnet. From this we have to subtract two, to compensate for Net- and Broadcast-Addresses."}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','MAC_TO_IID'::questionTypePrompt,'{"question": "Translate this MAC-Address to its IID (Interface Identifier):", "explanation": "Insert FF:FE in the middle of the address, and flip the seventh bit."}'::jsonb);
INSERT INTO promptQuestions (osilayer, questionTypePrompt, data) VALUES('L3_NETWORK','IID_TO_MAC'::questionTypePrompt,'{"question": "Translate this IID to its MAC equivalent:", "explanation": "Remove the FF:FE from the middle of the address and flip the seventh bit."}'::jsonb);

INSERT INTO questions (osilayer, difficulty, questiontype, data) VALUES
                                                                     ('L1_PHYSICAL', 'EASY', '{DEFINITIONS}'::questionTypeMC[], '{"question": "What is the primary function of the Physical layer?", "explanation": "The Physical layer is responsible for transmitting raw data bits over a communication channel.", "allAnswers": {"1": "Data Transmission", "2": "Routing", "3": "Encryption", "4": "Error Detection"}, "correctAnswers": ["1"]}'::jsonb),
                                                                     ('L2_DATA_LINK', 'MEDIUM', '{SWITCHING}'::questionTypeMC[], '{"question": "Which device operates primarily at the Data Link layer?", "explanation": "Switches operate at the Data Link layer by using MAC addresses to forward frames.", "allAnswers": {"1": "Switch", "2": "Router", "3": "Firewall", "4": "Hub"}, "correctAnswers": ["1"]}'::jsonb),
                                                                     ('L3_NETWORK', 'DIFFICULT', '{IPV4}'::questionTypeMC[], '{"question": "What is the default subnet mask for a Class B IPv4 address?", "explanation": "Class B networks use a default subnet mask of 255.255.0.0.", "allAnswers": {"1": "255.255.255.0", "2": "255.255.0.0", "3": "255.0.0.0", "4": "255.255.255.255"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L4_TRANSPORT', 'EASY', '{TCP}'::questionTypeMC[], '{"question": "Which transport layer protocol ensures reliable delivery of data?", "explanation": "TCP provides reliable, connection-oriented communication.", "allAnswers": {"1": "TCP", "2": "UDP", "3": "ICMP", "4": "HTTP"}, "correctAnswers": ["1"]}'::jsonb),
                                                                     ('L1_PHYSICAL', 'MEDIUM', '{DEFINITIONS}'::questionTypeMC[], '{"question": "What unit is used to measure data transmission speed at the Physical layer?", "explanation": "Data rates at the Physical layer are measured in bits per second (bps).", "allAnswers": {"1": "Bytes per second", "2": "Bits per second", "3": "Packets per second", "4": "Frames per second"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L2_DATA_LINK', 'DIFFICULT', '{SWITCHING}'::questionTypeMC[], '{"question": "What protocol is commonly used for VLAN trunking?", "explanation": "IEEE 802.1Q is the standard for VLAN tagging in Ethernet networks.", "allAnswers": {"1": "STP", "2": "VTP", "3": "802.1Q", "4": "LLDP"}, "correctAnswers": ["3"]}'::jsonb),
                                                                     ('L3_NETWORK', 'EASY', '{NAT}'::questionTypeMC[], '{"question": "What does NAT stand for?", "explanation": "NAT stands for Network Address Translation, which maps private IPs to public IPs.", "allAnswers": {"1": "Network Address Translation", "2": "New Address Table", "3": "Network Allocation Table", "4": "Node Address Transfer"}, "correctAnswers": ["1"]}'::jsonb),
                                                                     ('L4_TRANSPORT', 'MEDIUM', '{UDP}'::questionTypeMC[], '{"question": "Which characteristic best describes UDP?", "explanation": "UDP is a connectionless transport layer protocol that does not guarantee delivery.", "allAnswers": {"1": "Reliable", "2": "Connectionless", "3": "Error-correcting", "4": "Uses handshaking"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L1_PHYSICAL', 'DIFFICULT', '{DEFINITIONS}'::questionTypeMC[], '{"question": "Which of the following is an example of a Layer 1 device?", "explanation": "A repeater is a Physical layer device that regenerates signals.", "allAnswers": {"1": "Switch", "2": "Router", "3": "Repeater", "4": "Firewall"}, "correctAnswers": ["3"]}'::jsonb),
                                                                     ('L2_DATA_LINK', 'EASY', '{SWITCHING}'::questionTypeMC[], '{"question": "What address type does a switch use to forward frames?", "explanation": "Switches use MAC addresses to make forwarding decisions.", "allAnswers": {"1": "IP Address", "2": "MAC Address", "3": "Port Address", "4": "Protocol Address"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L3_NETWORK', 'MEDIUM', '{IPV6}'::questionTypeMC[], '{"question": "How many bits are in an IPv6 address?", "explanation": "An IPv6 address consists of 128 bits.", "allAnswers": {"1": "32", "2": "64", "3": "128", "4": "256"}, "correctAnswers": ["3"]}'::jsonb),
                                                                     ('L4_TRANSPORT', 'DIFFICULT', '{TCP}'::questionTypeMC[], '{"question": "What is the purpose of the TCP three-way handshake?", "explanation": "The TCP handshake establishes a reliable connection between two hosts.", "allAnswers": {"1": "To identify the sender", "2": "To establish a reliable connection", "3": "To encrypt data", "4": "To assign port numbers"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L1_PHYSICAL', 'EASY', '{DEFINITIONS}'::questionTypeMC[], '{"question": "Which type of cable is commonly used for Ethernet connections?", "explanation": "Twisted pair cables (such as Cat5e and Cat6) are commonly used in Ethernet networking.", "allAnswers": {"1": "Coaxial", "2": "Twisted Pair", "3": "Fiber Optic", "4": "Serial"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L2_DATA_LINK', 'MEDIUM', '{SWITCHING}'::questionTypeMC[], '{"question": "What is the main function of the Spanning Tree Protocol (STP)?", "explanation": "STP prevents network loops in a switched network.", "allAnswers": {"1": "Route packets", "2": "Prevent loops", "3": "Assign IP addresses", "4": "Encrypt traffic"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L3_NETWORK', 'DIFFICULT', '{SUBNETTING}'::questionTypeMC[], '{"question": "How many usable hosts are in a /26 subnet?", "explanation": "A /26 subnet has 64 total addresses, with 62 usable for hosts.", "allAnswers": {"1": "62", "2": "126", "3": "30", "4": "14"}, "correctAnswers": ["1"]}'::jsonb),
                                                                     ('L4_TRANSPORT', 'EASY', '{UDP}'::questionTypeMC[], '{"question": "Which application commonly uses UDP?", "explanation": "DNS uses UDP for quick, connectionless query responses.", "allAnswers": {"1": "FTP", "2": "DNS", "3": "SSH", "4": "SMTP"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L1_PHYSICAL', 'DIFFICULT', '{IPV4}'::questionTypeMC[], '{"question": "What is the maximum cable length for a standard Ethernet connection using Cat5e?", "explanation": "The standard maximum length for Cat5e Ethernet cables is 100 meters.", "allAnswers": {"1": "50 meters", "2": "100 meters", "3": "150 meters", "4": "200 meters"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L2_DATA_LINK', 'EASY', '{DEFINITIONS}'::questionTypeMC[], '{"question": "Which sublayer of the Data Link layer is responsible for controlling access to the medium?", "explanation": "The MAC sublayer handles media access control.", "allAnswers": {"1": "LLC", "2": "MAC", "3": "ARP", "4": "IP"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L3_NETWORK', 'MEDIUM', '{NAT}'::questionTypeMC[], '{"question": "Which type of NAT allows multiple private IPs to share a single public IP?", "explanation": "PAT (Port Address Translation) allows many private IPs to share one public IP.", "allAnswers": {"1": "Static NAT", "2": "Dynamic NAT", "3": "PAT", "4": "One-to-One NAT"}, "correctAnswers": ["3"]}'::jsonb),
                                                                     ('L4_TRANSPORT', 'DIFFICULT', '{UDP}'::questionTypeMC[], '{"question": "Which field in the UDP header ensures data integrity?", "explanation": "The checksum field in the UDP header verifies data integrity.", "allAnswers": {"1": "Sequence Number", "2": "Checksum", "3": "Acknowledgment Number", "4": "Window Size"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L1_PHYSICAL', 'MEDIUM', '{SUBNETTING}'::questionTypeMC[], '{"question": "Which type of cable is used for long-distance, high-speed network connections?", "explanation": "Fiber optic cables are used for high-speed, long-distance transmissions.", "allAnswers": {"1": "Coaxial", "2": "Twisted Pair", "3": "Fiber Optic", "4": "Serial"}, "correctAnswers": ["3"]}'::jsonb),
                                                                     ('L2_DATA_LINK', 'DIFFICULT', '{IPV6}'::questionTypeMC[], '{"question": "Which protocol is used for IPv6 address resolution?", "explanation": "IPv6 uses the Neighbor Discovery Protocol (NDP) instead of ARP.", "allAnswers": {"1": "ARP", "2": "NDP", "3": "ICMPv6", "4": "DHCPv6"}, "correctAnswers": ["2"]}'::jsonb),
                                                                     ('L3_NETWORK', 'EASY', '{DEFINITIONS}'::questionTypeMC[], '{"question": "Which protocol provides logical addressing for network devices?", "explanation": "The Internet Protocol (IP) provides logical addressing.", "allAnswers": {"1": "IP", "2": "TCP", "3": "ARP", "4": "DHCP"}, "correctAnswers": ["1"]}'::jsonb),
                                                                     ('L4_TRANSPORT', 'MEDIUM', '{SUBNETTING}'::questionTypeMC[], '{"question": "Which transport layer protocol is typically used for real-time applications like VoIP?", "explanation": "UDP is preferred for real-time applications because it is faster and does not require retransmissions.", "allAnswers": {"1": "TCP", "2": "UDP", "3": "ICMP", "4": "IP"}, "correctAnswers": ["2"]}'::jsonb);