import { createSlice } from "@reduxjs/toolkit";

/**
 * The initial state of the navigation.
 *
 * @typedef {Object} NavigationState
 * @property {boolean} isOpen Indicates whether the navigation menu is open.
 * @property {boolean} isAnimating Indicates whether the navigation menu is currently animating.
 */
const initialState = {
  isOpen: false,
  isAnimating: false,
};

const navigationSlice = createSlice({
  name: "navigation",
  initialState,
  reducers: {
    /**
     * Updates the `isOpen` state for the navigation menu.
     *
     * @param {Object} state The current state of the navigation.
     * @param {Object} action The dispatched action.
     * @param {boolean} action.payload The new value for `isOpen`.
     */
    updateIsOpen(state, action) {
      state.isOpen = action.payload;
    },
    /**
     * Updates the `isAnimating` state for the navigation menu.
     *
     * @param {Object} state The current state of the navigation.
     * @param {Object} action The dispatched action.
     * @param {boolean} action.payload The new value for `isAnimating`.
     */
    updateIsAnimating(state, action) {
      state.isAnimating = action.payload;
    },
  },
});

// Export the action creators generated by the slice
export const { updateIsOpen, updateIsAnimating } = navigationSlice.actions;
// Export the reducer to be included in the store
export default navigationSlice.reducer;
