import { createSlice } from "@reduxjs/toolkit";

/**
 * The initial state for the user's game status.
 *
 * @typedef {Object} UserState
 * @property {number} tipps The number of available tips (starts at 5).
 * @property {number} life The number of remaining lives (starts at 5).
 */
const initialState = {
    tipps: 5,
    life: 5,
};

const userStateSlice = createSlice({
    name: "userState",
    initialState,
    reducers: {
        /**
         * Reduces the number of available tips by 1.
         *
         * @param {UserState} state The current state of the user.
         */
        reduceTipps(state, action) {
            state.tipps = state.tipps - 1;
        },
        /**
         * Adds 1 to the number of available tips.
         *
         * @param {UserState} state The current state of the user.
         */
        addTipps(state, action) {
            state.tipps = state.tipps + 1;
        },
        /**
         * Reduces the number of lives by 1, ensuring the user doesn't go below 0 lives.
         *
         * @param {UserState} state The current state of the user.
         */
        reduceLife(state, action) {
            if(state.life === 0) return state;

            state.life = state.life - 1;
        },
        /**
         * Adds 1 to the number of lives, ensuring the user doesn't exceed 5 lives.
         *
         * @param {UserState} state The current state of the user.
         */
        addLife(state, action) {
            if(state.life === 5) return state;

            state.life = state.life + 1;
        },
    },
});

// Export the action creators generated by the slice
export const { reduceTipps, addTipps, reduceLife, addLife } = userStateSlice.actions;
// Export the reducer to be included in the store
export default userStateSlice.reducer;